CREATE DOMAIN FONE AS
   VARCHAR(17);
CREATE DOMAIN ID AS
   SMALLINT
   NOT NULL;
CREATE DOMAIN NOME AS
   VARCHAR(60)
   NOT NULL;

CREATE TABLE AGENDA (
   CODIGO ID NOT NULL,
   NOME NOME NOT NULL,
   TELEFONE FONE
   );

SET TERM ^ ;

   CREATE TRIGGER AGENDA_INSERT FOR AGENDA
   ACTIVE BEFORE INSERT POSITION 0
   AS
   DECLARE VARIABLE COD INTEGER;
   begin
   if ((NEW.CODIGO IS NULL) or (NEW.CODIGO=0)) then
   begin
   SELECT MAX(CODIGO) FROM AGENDA INTO :COD;
   if (COD IS NULL) then
   COD=0;
   New.Codigo = Cod + 1;
   end
   end
   ^
SET TERM ;

/* INSERT INTO AGENDA (CODIGO, NOME, TELEFONE) VALUES (1, 'EDUARDO JEDLICZKA', '(43) 422-5962'); */