CREATE TABLE CONFIG(
  ID Integer NOT NULL,
  TIPO Varchar(20),
  SERVIDOR_NOME Varchar(100),
  CAMIN_BANCO Varchar(255),
  CAMIN_FOTOS Varchar(255),
  CAMIN_BACKUP Varchar(255),
  PORTA_IMP Varchar(10),
  ECF_TIPO Varchar(20),
  PRIMARY KEY (ID)
);

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CONFIG TO  SYSDBA WITH GRANT OPTION;

CREATE TABLE CLIENTES(
  ID Bigint NOT NULL,
  DATA_CAD Date,
  NOME Varchar(255),
  RAZAO Varchar(255),
  TIPO Varchar(10),
  CPF Varchar(20),
  RG Varchar(20),
  CNPJ Varchar(20),
  IE Varchar(20),
  ENDERECO Varchar(255),
  BAIRRO Varchar(255),
  CIDADE Varchar(255),
  ESTADO Char(2),
  CEP Varchar(20),
  CAIXA_POSTAL Varchar(10),
  FONE1 Varchar(20),
  FONE2 Varchar(20),
  CEL1 Varchar(20),
  CEL2 Varchar(20),
  FAX1 Varchar(20),
  FAX2 Varchar(20),
  CONTATO Varchar(255),
  EMAIL1 Varchar(255),
  EMAIL2 Varchar(255),
  SITE Varchar(255),
  OBS Blob sub_type 1,
  FOTO Varchar(255),
  ATIVO Varchar(4),
  PRIMARY KEY (ID)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CLIENTES TO  SYSDBA WITH GRANT OPTION;

CREATE TABLE EMPRESA(
  ID integer NOT NULL,
  NOME Varchar(255),
  RAZAO Varchar(255),
  CNPJ Varchar(20),
  IE Varchar(20),
  ENDERECO Varchar(255),
  BAIRRO Varchar(255),
  CIDADE Varchar(255),
  ESTADO Char(2),
  CEP Varchar(20),
  CAIXA_POSTAL Varchar(10),
  FONE1 Varchar(20),
  FONE2 Varchar(20),
  CEL1 Varchar(20),
  CEL2 Varchar(20),
  FAX1 Varchar(20),
  FAX2 Varchar(20),
  EMAIL1 Varchar(255),
  EMAIL2 Varchar(255),
  SITE Varchar(255),
  LOGOTIPO Blob sub_type 0,
  PRIMARY KEY (ID)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON EMPRESA TO  SYSDBA WITH GRANT OPTION;

CREATE TABLE FORNECEDORES(
  ID Bigint NOT NULL,
  DATA_CAD Date,
  NOME Varchar(255),
  RAZAO Varchar(255),
  CNPJ Varchar(20),
  IE Varchar(20),
  ENDERECO Varchar(255),
  BAIRRO Varchar(255),
  CIDADE Varchar(255),
  ESTADO Char(2),
  CEP Varchar(20),
  CAIXA_POSTAL Varchar(10),
  FONE1 Varchar(20),
  FONE2 Varchar(20),
  CEL1 Varchar(20),
  CEL2 Varchar(20),
  FAX1 Varchar(20),
  FAX2 Varchar(20),
  CONTATO Varchar(255),
  ATIVO Smallint,
  EMAIL1 Varchar(255),
  EMAIL2 Varchar(255),
  SITE Varchar(255),
  OBS Blob sub_type 1,
  PRIMARY KEY (ID)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON FORNECEDORES TO  SYSDBA WITH GRANT OPTION;

CREATE TABLE GRUPOS(
  ID Bigint NOT NULL,
  GRUPO Varchar(255),
  PRIMARY KEY (ID)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON GRUPOS TO  SYSDBA WITH GRANT OPTION;

CREATE TABLE MARCAS(
  ID Bigint NOT NULL,
  MARCA Varchar(255),
  PRIMARY KEY (ID)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON MARCAS TO  SYSDBA WITH GRANT OPTION;

CREATE TABLE MODELOS(
  ID Bigint NOT NULL,
  MODELO Varchar(255),
  PRIMARY KEY (ID)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON MODELOS TO  SYSDBA WITH GRANT OPTION;

CREATE TABLE UNIDADES(
  ID Bigint NOT NULL,
  UNIDADE Varchar(255),
  PRIMARY KEY (ID)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON MODELOS TO  SYSDBA WITH GRANT OPTION;

CREATE TABLE PRODUTOS(
  ID Bigint NOT NULL,
  COD_BARRA Varchar(100),
  DATA_CAD Date,
  DESCRICAO Varchar(255),
  GRUPO Bigint,
  MARCA Bigint,
  MODELO Bigint,
  FORNECEDOR Bigint,
  ESTOQUE_MIN Float,
  ESTOQUE_ATUAL Float,
  REFERENCIA Varchar(30),
  OBS Blob sub_type 1,
  FOTO Varchar(255),
  UNIDADE Integer,
  PRECO_COMP Double precision,
  PRECO_VEND Double precision,
  PRIMARY KEY (ID)
);

ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_1
  FOREIGN KEY (GRUPO) REFERENCES GRUPOS (ID) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_2
  FOREIGN KEY (MARCA) REFERENCES MARCAS (ID) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_3
  FOREIGN KEY (MODELO) REFERENCES MODELOS (ID) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_4
  FOREIGN KEY (FORNECEDOR) REFERENCES FORNECEDORES (ID) ON UPDATE CASCADE ON DELETE SET NULL;
/* ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_5
  FOREIGN KEY (UNIDADE) REFERENCES UNIDADES (ID) ON UPDATE CASCADE ON DELETE SET NULL; */
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON PRODUTOS TO  SYSDBA WITH GRANT OPTION;

CREATE GENERATOR GEN_CLIENTES_ID;
CREATE GENERATOR GEN_FORNECEDORES_ID;
CREATE GENERATOR GEN_GRUPOS_ID;
CREATE GENERATOR GEN_MARCAS_ID;
CREATE GENERATOR GEN_MODELOS_ID;
CREATE GENERATOR GEN_PRODUTOS_ID;
CREATE GENERATOR GEN_UNIDADES_ID;

SET TERM ^ ;
CREATE TRIGGER CLIENTES_BI FOR CLIENTES ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CLIENTES_ID, 1);
END^
SET TERM ; ^

SET TERM ^ ;
CREATE TRIGGER FORNECEDORES_BI FOR FORNECEDORES ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_FORNECEDORES_ID, 1);
END^
SET TERM ; ^

SET TERM ^ ;
CREATE TRIGGER GRUPOS_BI FOR GRUPOS ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_GRUPOS_ID, 1);
END^
SET TERM ; ^

SET TERM ^ ;
CREATE TRIGGER MARCAS_BI FOR MARCAS ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_MARCAS_ID, 1);
END^
SET TERM ; ^

SET TERM ^ ;
CREATE TRIGGER MODELOS_BI FOR MODELOS ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_MODELOS_ID, 1);
END^
SET TERM ; ^

SET TERM ^ ;
CREATE TRIGGER PRODUTOS_BI FOR PRODUTOS ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_PRODUTOS_ID, 1);
END^
SET TERM ; ^

SET TERM ^ ;
CREATE TRIGGER UNIDADES_BI FOR UNIDADES ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_UNIDADES_ID, 1);
END^
SET TERM ; ^